Repository Nihongo-Jouzu/nihongo-jouzu-frontend, pull requests merged in 2024-09, with the labels that each got.

#8 Selectgame UI
  README.md
  components/game/findPairGame/start.tsx
  components/game/newExpression/mainCard.tsx
  components/game/newExpression/phraseList.tsx
  components/game/newExpression/start.tsx
  components/game/practice/start.tsx
  components/header.tsx
  next.config.mjs
  pages/404.tsx
  pages/_app.tsx
  pages/api/auth/[...nextauth].ts
  pages/game/learning.tsx
  pages/index.tsx
  pages/login.tsx
  pages/selectGame.tsx
  public/new-expression-fox.png
  public/practice-nife.png
  types/types.ts
Labels: enhancement

#10 Auth backend
  package-lock.json
  package.json
  pages/api/auth/[...nextauth].js
  pages/api/auth/[...nextauth].ts
  pages/index.tsx
  pages/mypage.tsx
  tsconfig.json
  types/next-auth.d.ts
  types/types.ts
Labels: enhancement

#12 Auto test frontend example with Jest
  .env.example
  README.md
  __tests__/pages/404.test.tsx
  __tests__/pages/learning.test.tsx
  __tests__/pages/login.test.tsx
  __tests__/pages/selectGame.test.tsx
  components/game/newExpression/phraseList.tsx
  jest.config.ts
  package-lock.json
  package.json
  pages/game/learning.tsx
  utils/mocks-tsx.tsx
  utils/mocks.ts
Labels: test

#14 4 feature web socket setup
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  __tests__/pages/404.test.tsx
  __tests__/pages/learning.test.tsx
  __tests__/pages/login.test.tsx
  __tests__/pages/selectGame.test.tsx
  components/GamePair.tsx
  components/GameQuickAnswer.tsx
  components/GameStateProvider.tsx
  components/SocketProvider.tsx
  components/game/PlayerList.tsx
  components/game/findPairGame/Card.tsx
  components/game/findPairGame/Matrix.tsx
  components/game/newExpression/mainCard.tsx
  components/game/newExpression/phraseList.tsx
  components/game/newExpression/start.tsx
  components/game/practice/start.tsx
  components/header.tsx
  data/data.json
  globals/types/game.ts
  globals/types/next.ts
  jest.config.ts
  next.config.mjs
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/api/data.ts
  pages/api/hello.ts
  pages/api/socket.ts
  pages/game/findPair.tsx
  pages/game/learning.tsx
  pages/game/quickAnswer.tsx
  pages/login.tsx
  pages/mypage.tsx
  pages/selectGame.tsx
  styles/globals.css
  types/game.d.ts
  types/types.ts
  utils/mocks-tsx.tsx
  utils/mocks.ts
  utils/utils-data.ts
  utils/utils-session.ts
Labels: enhancement

#19 Docker change
  .dockerignore
  Dockerfile
  Dockerfile-local
  next.config.mjs
  package-lock.json
  package.json
Labels: bug

#27 Create node.js.yml
  .github/workflows/node.js.yml
Labels: enhancement

#37 [STYLE] Improve design of game pair
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  components/GamePair.tsx
  components/game/PlayerList.tsx
  components/game/PlayerShow.tsx
  components/game/ScoreCircle.tsx
  components/game/Winner.tsx
  components/game/findPairGame/Card.tsx
  components/game/findPairGame/Matrix.tsx
  components/game/flashCard/FlashCard.tsx
  pages/api/auth/[...nextauth].js
  pages/api/backend.ts
  pages/api/socket.ts
  pages/game/find-pair.tsx
  pages/game/game-result.tsx
  pages/lobby.tsx
  pages/mypage.tsx
  public/ninjaLogo.svg
  styles/Card.module.css
  styles/FlashCard.module.css
  styles/Game.module.css
  styles/GameResult.module.css
  styles/globals.css
  types/game.d.ts
  utils/utils-data.ts
Labels: Style

#42 new flashcards
  components/game/flashCard/FlashCard.tsx
  components/game/flashCard/PhraseList.tsx
  pages/game/expression.tsx
  pages/game/flash-card.tsx
  styles/FlashCard.module.css
Labels: enhancement

#53 48 featureimprove landing page appearance and links
  __tests__/pages/login.test.tsx
  __tests__/pages/select-game.test.tsx
  components/Footer.tsx
  components/Header.tsx
  components/Layouts.tsx
  middleware.ts
  pages/game/expression.tsx
  pages/game/flash-card.tsx
  pages/index.tsx
  pages/login.tsx
  pages/select-game.tsx
  public/LandingPage/landpage.svg
  public/LandingPage/landpage_md.jpeg
  styles/globals.css
Labels: enhancement

#62 Modals for homepage
  components/modal.tsx
  package-lock.json
  package.json
  pages/api/auth/[...nextauth].js
  pages/auth/credentials-signin.tsx
  pages/index.tsx
  pages/signup.tsx
Labels: enhancement

#66 [FIX] Fetch for flashcards and expression is missing
  components/game/flashCard/FlashCard.tsx
  components/game/newWords/MainCard.tsx
  components/game/newWords/PhraseList.tsx
  pages/api/backend.ts
  pages/game/expression.tsx
  pages/game/flash-card.tsx
  pages/lobby.tsx
  utils/utils-data.ts
Labels: enhancement

#72 [BUG] Add bottom padding to body
  components/Layouts.tsx
  pages/lobby.tsx
Labels: bug

#68 message when a player disconnect and leave game button finished
  components/game/PlayerList.tsx
  components/game/findPairGame/Message.tsx
  components/modal.tsx
  pages/game/find-pair.tsx
Labels: bug

#79 feat:Update message
  components/game/Draw.tsx
Labels: enhancement

#81 [FEATURE] Prevent user disconnect and join when lobby is full
  .vscode/extensions.json
  components/game/findPairGame/Matrix.tsx
  pages/api/socket.ts
  pages/game/find-pair.tsx
  pages/mypage.tsx
  types/game.d.ts
  utils/utils-socket.ts
Labels: bug, enhancement

#85 Feat: Delete lobby after game start
  pages/api/socket.ts
  pages/lobby.tsx
Labels: enhancement

#88 [FIX] Bug App crush after login failure
  pages/api/auth/[...nextauth].js
  pages/auth/credentials-signin.tsx
  pages/index.tsx
Labels: bug

#94 [STYLE] Improve game pair style
  components/GamePair.tsx
  components/Layouts.tsx
  components/game/PlayerList.tsx
  components/game/PlayerShow.tsx
  components/game/findPairGame/Card.tsx
  components/game/findPairGame/Matrix.tsx
  components/game/findPairGame/Message.tsx
  pages/_app.tsx
  pages/game/find-pair.tsx
  styles/Card.module.css
  styles/Game.module.css
  styles/globals.css
Labels: Style

#96 Fix: Double login
  __tests__/pages/learning.test.tsx
  components/GameQuickAnswer.tsx
  components/game/newWords/MainCard.tsx
  components/game/newWords/PhraseList.tsx
  components/game/newWords/learning.tsx
  pages/api/auth/[...nextauth].js
  pages/auth/credentials-signin.tsx
  pages/game/quick-answer.tsx
  pages/game/quickAnswer.tsx
  pages/index.tsx
Labels: bug

#83 78 bug expression page design improvement
  pages/game/expression.tsx
Labels: Style

#104 navbar task
  components/Header.tsx
Labels: bug

#106 Fix: Game on mobile responsive
  components/game/PlayerList.tsx
  components/game/findPairGame/Message.tsx
  pages/game/find-pair.tsx
  styles/Card.module.css
Labels: bug

#113 [FIX] Login/Signup redirect and username to lowercase
  pages/api/auth/[...nextauth].js
  pages/auth/credentials-signin.tsx
  pages/auth/signup.tsx
  pages/index.tsx
  pages/signup.tsx
Labels: bug

#119 111 bugevery time user will see draw page regardless of the game result
  __tests__/pages/game-result.test.tsx
  pages/game/game-result.tsx
Labels: bug

#121 120 Add note on signup page about the special charater
  pages/auth/signup.tsx
Labels: enhancement

#118 Fix: Lobby redirect
  components/game/findPairGame/Card.tsx
  pages/api/socket.ts
  pages/game/find-pair.tsx
  styles/Card.module.css
  types/game.d.ts
Labels: bug

#142 142 Change style in find pair game.
  components/game/PlayerShow.tsx
Labels: enhancement

#140 139 feature brush up lobby design
  pages/lobby.tsx
Labels: enhancement

#143 136 feature readme
  README.development.md
  README.md
  components/Footer.tsx
  components/game/Draw.tsx
  components/game/ScoreCircle.tsx
  components/game/findPairGame/Draw.tsx
  components/game/findPairGame/GamePair.tsx
  components/game/findPairGame/Message.tsx
  components/game/findPairGame/Winner.tsx
  pages/api/socket.ts
  pages/game/find-pair.tsx
  pages/game/game-result.tsx
Labels: Style
